"""
1. Develop source codes ("main program") with name lab8.c define two functions (1)
computing factorial of an integer n and (2) computing exponential of a real number x.
* For computing factorial(n), define a function with recursive calls.
*For computing exp(x), define a function with Taylor expansions (recall Python codes), where, the constant
e= 2.718281828459, x0 = round(x) is the closest integert to x, and use the pow(.,.) from math.h
for computing powers. Use your own function.
*Generate a set of points x = 0, 0.02, 0.04, . . ., 0.98, 1, compute 
exp(x) at the given points (with your own function).
*Output the data to a data file, and visualize the exp(x) function 
with the data in python
2. Update Git repository
3. Submit codes, output data file and screenshots.
"""

import numpy as np
import matplotlib.pyplot as plt

#Compile and run the C program to generate the data file
import os
os.system('gcc lab8.c -o lab8 -lm')
os.system('./lab8')

# Load data from the output file generated by lab8.c
data = np.loadtxt('exp_data.txt')
x_values = data[:, 0]
exp_values = data[:, 1]

# Plotting the results
plt.figure(figsize=(10, 6))
plt.plot(x_values, exp_values, label='exp(x) from lab8.c', color='blue', marker='o', markersize=4)
plt.title('Exponential Function exp(x) Computed from lab8.c')
plt.xlabel('x')
plt.ylabel('exp(x)')
plt.grid(True)
plt.legend()
plt.savefig('exp_function_lab8.png')
plt.show()